const { contextBridge, ipcRenderer } = require("electron")

contextBridge.exposeInMainWorld("electronBridge", {
    platform:     process.platform,
    readFile:     (root, path)          => ipcRenderer.invoke("fs:read",           root, path),
    writeFile:    (root, path, content) => ipcRenderer.invoke("fs:write",          root, path, content),
    pickFolder:   ()                    => ipcRenderer.invoke("fs:pick-folder"),
    getFileTree:  (root)                => ipcRenderer.invoke("fs:tree",           root),
    getEndpoint:  ()                    => ipcRenderer.invoke("cfg:get-endpoint"),
    setEndpoint:  (url)                 => ipcRenderer.invoke("cfg:set-endpoint",  url),
    getLocalPath:  (projectId)                       => ipcRenderer.invoke("project:get-path",  projectId),
    setLocalPath:  (projectId, path)                 => ipcRenderer.invoke("project:set-path",  projectId, path),
    listDirectory: (root, dirPath)                   => ipcRenderer.invoke("fs:list-dir",        root, dirPath),
    searchFiles:   (root, pattern, searchPath, glob, ignoreCase) => ipcRenderer.invoke("fs:search", root, pattern, searchPath, glob, ignoreCase),
    editFile:      (root, filePath, newStr, options) => ipcRenderer.invoke("fs:edit",     root, filePath, newStr, options),
    runCommand:          (root, command) => ipcRenderer.invoke("fs:run",            root, command),
    findFiles:           (root, pattern, searchPath) => ipcRenderer.invoke("fs:find",   root, pattern, searchPath),
    deleteFile:          (root, filePath)            => ipcRenderer.invoke("fs:delete", root, filePath),
    moveFile:            (root, source, destination) => ipcRenderer.invoke("fs:move",   root, source, destination),
    getCommandAllowlist: ()              => ipcRenderer.invoke("cmd:get-allowlist"),
    setCommandAllowlist: (list)          => ipcRenderer.invoke("cmd:set-allowlist", list),
    moveWindowBy:   (dx, dy) => ipcRenderer.invoke("window:move-by",  dx, dy),
    closeWindow:    ()       => ipcRenderer.invoke("window:close"),
    minimizeWindow: ()       => ipcRenderer.invoke("window:minimize"),
    maximizeWindow: ()       => ipcRenderer.invoke("window:maximize"),
    markReady:    ()                    => ipcRenderer.invoke("app:ready"),
    getVersion:   ()                    => ipcRenderer.invoke("app:version"),
})
